---
title: "data_wrangling_ii"
author: "Leila Yan"
date: "2024-10-09"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```
## Scape a table

I want the first table from [this page]: https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm

read in the html
```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

extract the table(s); focus on the first one
```{r}
table
drug_use_html %>%
  html_nodes(css = "table") %>%
  first() %>% # not working!!!
  html_table() %>% 
  slice(-1) %>% #removes the first row
  as_tibble()

table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1) 

table_marj
```
## Star Wars movie info
```{r}
url = "https://www.imdb.com/list/ls070150896/"
swm_html = 
  read_html(url)
```

grab elements that i want
```{r}
title_vec = 
  swm_html %>%
  html_nodes (css = ".lister-item-header a") %>% #extract html nodes
  html_text() 

gross_rev_vec = 
  swm_html %>%
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)" ) %>%
  html_text()

# to know how long the movie is
runtime_vec= 
  swm_html %>%
  html_nodes(css = ".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    gross_rev = gross_rev_vec,
    runtime = runtime_vec)
```

## get some water data
this is from an API
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content("parsed")

nyc_water = GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

## BRFSS
same process different data

```{r}
brfss_2010 =
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% #it gives 5000 rows
  content("parsed")
```

## some data aren't so nice

let's look at pokemon
```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()

poke[["name"]]

poke$name
poke$height
poke$abilities
```


### Strings and vector - Second lecture
```{r}
library(rvest)
library(p8105.datasets)
library(tidyverse)
```



```{r}
string_vec = c("my", "name", "is", "jeff")
str_detect(string_vec, "jeff")
str_replace(string_vec, "jeff", "jeff")
str_replace(string_vec, "j", "jeff")
```


```{r}
string_vec= c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun",
  "it will be fun, i think"
)

str_detect(string_vec, "i think")
# i think shows up in all 4 statements


str_detect(string_vec, "^i think")
# detect something that begins with i think

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember pres. Hw Bush?",
  "i saw a green bush",
  "BBQ an Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "Bush")
# only detect Bush that starts with "B", capital

str_detect(string_vec, "[Bb]ush")
# capital and lower case B
```

```{r}
string_vec = c(
  "7th inning stretch",
  "1st half soon to begin. Texas won the toss.",
  "she is 5 feet 4 inches tall",
  "3AM - cant sleep :("
)

str_detect(string_vec, "[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
# catch statement1, 2, 4; miss 3
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
# Some characters are “special”. These include [ and ], ( and ), and . If you want to search for these, you have to indicate they’re special using \. Unfortunately, \ is also special, so things get weird.
```

## Factors
```{r}
factor_vec = factor(c("male", "male", "female", "female"))
factor_vec

as.numeric(factor_vec)
```

what happens if i relevel?
```{r}
factor_vec = fct_relevel(factor_vec, "male")

factor_vec

as.numeric(factor_vec)
```



## NSDUH

















